// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Idorder              string   `protobuf:"bytes,1,opt,name=idorder,proto3" json:"idorder,omitempty"`
	Item                 string   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetIdorder() string {
	if m != nil {
		return m.Idorder
	}
	return ""
}

func (m *Order) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetOrderReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderReq) Reset()         { *m = GetOrderReq{} }
func (m *GetOrderReq) String() string { return proto.CompactTextString(m) }
func (*GetOrderReq) ProtoMessage()    {}
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{1}
}

func (m *GetOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderReq.Unmarshal(m, b)
}
func (m *GetOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderReq.Marshal(b, m, deterministic)
}
func (m *GetOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderReq.Merge(m, src)
}
func (m *GetOrderReq) XXX_Size() int {
	return xxx_messageInfo_GetOrderReq.Size(m)
}
func (m *GetOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderReq proto.InternalMessageInfo

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Order                *Order   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Orders               []*Order `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Response) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*GetOrderReq)(nil), "order.GetOrderReq")
	proto.RegisterType((*Response)(nil), "order.Response")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor_986e030a471601a2) }

var fileDescriptor_986e030a471601a2 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xdd, 0x6e, 0xb7, 0xae, 0x93, 0x8a, 0x30, 0x08, 0x06, 0x4f, 0x21, 0x78, 0xe8, 0x69,
	0xc5, 0xfa, 0x08, 0x1e, 0x3c, 0x0a, 0xf1, 0x09, 0x34, 0x99, 0x43, 0x0e, 0xdd, 0xa4, 0x49, 0xf0,
	0xf9, 0xa5, 0x93, 0x0d, 0x54, 0xec, 0x65, 0x99, 0xff, 0xff, 0x77, 0x32, 0xdf, 0x0c, 0x3c, 0xc4,
	0x14, 0x4a, 0x78, 0x0e, 0xc9, 0x51, 0xaa, 0xdf, 0x89, 0x1d, 0x1c, 0x58, 0xe8, 0x03, 0x0c, 0x1f,
	0xa7, 0x02, 0x25, 0x5c, 0x7b, 0xc7, 0x9e, 0xec, 0x54, 0xb7, 0xbb, 0x31, 0x4d, 0x22, 0xc2, 0xda,
	0x17, 0x3a, 0xc8, 0x15, 0xdb, 0x5c, 0xa3, 0x02, 0xe1, 0x28, 0xdb, 0xe4, 0x63, 0xf1, 0x61, 0x96,
	0x3d, 0x47, 0xe7, 0x16, 0xde, 0xc3, 0x10, 0x93, 0xb7, 0x24, 0xd7, 0xaa, 0xdb, 0xad, 0x4c, 0x15,
	0xfa, 0x16, 0xc4, 0x3b, 0x15, 0x9e, 0x68, 0xe8, 0xa8, 0x67, 0x18, 0x0d, 0xe5, 0x18, 0xe6, 0x4c,
	0x27, 0x00, 0x9b, 0xe8, 0xab, 0x90, 0x63, 0x80, 0xd1, 0x34, 0x89, 0x1a, 0x2a, 0x2c, 0x13, 0x88,
	0xfd, 0x76, 0xaa, 0x7b, 0xd4, 0x57, 0x6a, 0x84, 0x4f, 0xb0, 0xe1, 0x22, 0xcb, 0x5e, 0xf5, 0xff,
	0x7e, 0x5a, 0xb2, 0xfd, 0x11, 0xb6, 0x6c, 0x7c, 0x52, 0xfa, 0xf1, 0x96, 0x70, 0x02, 0xf1, 0xc6,
	0x43, 0xea, 0x0d, 0xfe, 0x34, 0x3d, 0xde, 0x2d, 0xaa, 0x11, 0xea, 0x2b, 0x7c, 0x81, 0xb1, 0xe1,
	0x23, 0x2e, 0xf1, 0xd9, 0x3e, 0x17, 0x5a, 0xbe, 0x37, 0x7c, 0xee, 0xd7, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xce, 0x2b, 0xbb, 0xd5, 0x89, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderService service

type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *Order, opts ...client.CallOption) (*Response, error)
	GetOrder(ctx context.Context, in *GetOrderReq, opts ...client.CallOption) (*Response, error)
}

type orderServiceClient struct {
	c           client.Client
	serviceName string
}

func NewOrderServiceClient(serviceName string, c client.Client) OrderServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "order"
	}
	return &orderServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.CreateOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.GetOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	CreateOrder(context.Context, *Order, *Response) error
	GetOrder(context.Context, *GetOrderReq, *Response) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&OrderService{hdlr}, opts...))
}

type OrderService struct {
	OrderServiceHandler
}

func (h *OrderService) CreateOrder(ctx context.Context, in *Order, out *Response) error {
	return h.OrderServiceHandler.CreateOrder(ctx, in, out)
}

func (h *OrderService) GetOrder(ctx context.Context, in *GetOrderReq, out *Response) error {
	return h.OrderServiceHandler.GetOrder(ctx, in, out)
}
