// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import models "gitlab.warungpintar.co/enrinal/intern-diary/simple-order/models"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// ChangeOrderDelivered provides a mock function with given fields: ctx, ID
func (_m *Repository) ChangeOrderDelivered(ctx context.Context, ID int64) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeOrderProcess provides a mock function with given fields: ctx, ID
func (_m *Repository) ChangeOrderProcess(ctx context.Context, ID int64) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeOrderSend provides a mock function with given fields: ctx, ID
func (_m *Repository) ChangeOrderSend(ctx context.Context, ID int64) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllOrder provides a mock function with given fields: ctx, num
func (_m *Repository) GetAllOrder(ctx context.Context, num int64) ([]*models.Order, error) {
	ret := _m.Called(ctx, num)

	var r0 []*models.Order
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.Order); ok {
		r0 = rf(ctx, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllOrderById provides a mock function with given fields: ctx, ID
func (_m *Repository) GetAllOrderById(ctx context.Context, ID int64) ([]*models.Order, error) {
	ret := _m.Called(ctx, ID)

	var r0 []*models.Order
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.Order); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderById provides a mock function with given fields: ctx, ID
func (_m *Repository) GetOrderById(ctx context.Context, ID int64) (*models.Order, error) {
	ret := _m.Called(ctx, ID)

	var r0 *models.Order
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Order); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
