// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "gitlab.warungpintar.co/enrinal/intern-diary/simple-order/models"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// ChangeOrderDelivered provides a mock function with given fields: ID
func (_m *Usecase) ChangeOrderDelivered(ID int64) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeOrderProcess provides a mock function with given fields: ID
func (_m *Usecase) ChangeOrderProcess(ID int64) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeOrderSend provides a mock function with given fields: ID
func (_m *Usecase) ChangeOrderSend(ID int64) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountOrderCust provides a mock function with given fields: ID
func (_m *Usecase) CountOrderCust(ID int64) int {
	ret := _m.Called(ID)

	var r0 int
	if rf, ok := ret.Get(0).(func(int64) int); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetAllOrder provides a mock function with given fields:
func (_m *Usecase) GetAllOrder() ([]*models.Order, error) {
	ret := _m.Called()

	var r0 []*models.Order
	if rf, ok := ret.Get(0).(func() []*models.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllOrderById provides a mock function with given fields: ID
func (_m *Usecase) GetAllOrderById(ID int64) ([]*models.Order, error) {
	ret := _m.Called(ID)

	var r0 []*models.Order
	if rf, ok := ret.Get(0).(func(int64) []*models.Order); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderById provides a mock function with given fields: ID
func (_m *Usecase) GetOrderById(ID int64) (*models.Order, error) {
	ret := _m.Called(ID)

	var r0 *models.Order
	if rf, ok := ret.Get(0).(func(int64) *models.Order); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderStatus provides a mock function with given fields: ID
func (_m *Usecase) GetOrderStatus(ID int64) string {
	ret := _m.Called(ID)

	var r0 string
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
