version: "2.3"
services:
  web:
    image: simple-order-system
    container_name: order_system_api
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./config.json:/app/config.json
  mysql:
    image: mariadb
    container_name: order_system_mysql
    restart: always
    command: mysqld --user=root
    volumes:
      - ./simpleorder.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=simpleorder
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
